export const SWITCH_TYPE = "SWITCH_TYPE";
export const MENU_TYPE = "MENU_TYPE";
export const SUB_MENU_TYPE = "SUB_MENU_TYPE";
export const PAGE_TYPE = "PAGE_TYPE";
export const STATIC_TYPE = "STATIC_TYPE";

// Permissions annotations

export const MAIN_MENU = "MAIN_MENU";

// Statistics

export const STA_MENU = "STA_MENU";

// Cheques

export const STA_CHEQUE = "STA_CHEQUE";
export const STA_CHEQUE_LIST = "STA_CHEQUE_LIST";

export const STA_CHEQUE_LIST_STAT = "STA_CHEQUE_LIST_STAT";
export const STA_CHEQUE_LIST_STAT_RECEIPTS = "STA_CHEQUE_LIST_STAT_RECEIPTS";
export const STA_CHEQUE_LIST_STAT_NDS = "STA_CHEQUE_LIST_STAT_NDS";
export const STA_CHEQUE_LIST_STAT_POSITIONS_IN_RECEIPTS = "STA_CHEQUE_LIST_STAT_POSITIONS_IN_RECEIPTS";
export const STA_CHEQUE_LIST_STAT_REVENUE = "STA_CHEQUE_LIST_STAT_REVENUE";
export const STA_CHEQUE_LIST_STAT_DISCOUNT = "STA_CHEQUE_LIST_STAT_DISCOUNT";
export const STA_CHEQUE_LIST_STAT_CASH = "STA_CHEQUE_LIST_STAT_CASH";
export const STA_CHEQUE_LIST_STAT_CARD = "STA_CHEQUE_LIST_STAT_CARD";
export const STA_CHEQUE_LIST_STAT_CARD_UZCARD = "STA_CHEQUE_LIST_STAT_CARD_UZCARD";
export const STA_CHEQUE_LIST_STAT_CARD_HUMO = "STA_CHEQUE_LIST_STAT_CARD_HUMO";
export const STA_CHEQUE_LIST_STAT_CARD_LOYALTY = "STA_CHEQUE_LIST_STAT_CARD_LOYALTY";
export const STA_CHEQUE_LIST_STAT_CARD_OTHER = "STA_CHEQUE_LIST_STAT_CARD_OTHER";

export const STA_CHEQUE_LIST_FILT = "STA_CHEQUE_LIST_FILT";
export const STA_CHEQUE_LIST_FILT_DATE = "STA_CHEQUE_LIST_FILT_DATE";
export const STA_CHEQUE_LIST_FILT_SEARCH = "STA_CHEQUE_LIST_FILT_SEARCH";
export const STA_CHEQUE_LIST_FILT_COMPANY = "STA_CHEQUE_LIST_FILT_COMPANY";
export const STA_CHEQUE_LIST_FILT_BRANCH = "STA_CHEQUE_LIST_FILT_BRANCH";
export const STA_CHEQUE_LIST_FILT_EMPLOYEE = "STA_CHEQUE_LIST_FILT_EMPLOYEE";
export const STA_CHEQUE_LIST_FILT_CHEQUE_TYPE = "STA_CHEQUE_LIST_FILT_CHEQUE_TYPE";
export const STA_CHEQUE_LIST_FILT_PRICE = "STA_CHEQUE_LIST_FILT_PRICE";

export const STA_CHEQUE_DETAILS = "STA_CHEQUE_DETAILS";

// Cheques by branch

export const STA_CHEQUE_BY_BRANCH = "STA_CHEQUE_BY_BRANCH";
export const STA_CHEQUE_BY_BRANCH_LIST = "STA_CHEQUE_BY_BRANCH_LIST";

export const STA_CHEQUE_BY_BRANCH_LIST_STAT = "STA_CHEQUE_BY_BRANCH_LIST_STAT";
export const STA_CHEQUE_BY_BRANCH_LIST_STAT_BRANCH = "STA_CHEQUE_BY_BRANCH_LIST_STAT_BRANCH";
export const STA_CHEQUE_BY_BRANCH_LIST_STAT_CHEQUE = "STA_CHEQUE_BY_BRANCH_LIST_STAT_CHEQUE";
export const STA_CHEQUE_BY_BRANCH_LIST_STAT_REVENUE = "STA_CHEQUE_BY_BRANCH_LIST_STAT_REVENUE";

export const STA_CHEQUE_BY_BRANCH_LIST_FILT = "STA_CHEQUE_BY_BRANCH_LIST_FILT";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_DATE = "STA_CHEQUE_BY_BRANCH_LIST_FILT_DATE";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_SEARCH = "STA_CHEQUE_BY_BRANCH_LIST_FILT_SEARCH";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_COMPANY = "STA_CHEQUE_BY_BRANCH_LIST_FILT_COMPANY";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_REGION = "STA_CHEQUE_BY_BRANCH_LIST_FILT_REGION";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_CITY = "STA_CHEQUE_BY_BRANCH_LIST_FILT_CITY";
export const STA_CHEQUE_BY_BRANCH_LIST_FILT_ACTIVITY = "STA_CHEQUE_BY_BRANCH_LIST_FILT_ACTIVITY";

// Cheques by company

export const STA_CHEQUE_BY_COMPANY = "STA_CHEQUE_BY_COMPANY";
export const STA_CHEQUE_BY_COMPANY_LIST = "STA_CHEQUE_BY_COMPANY_LIST";

export const STA_CHEQUE_BY_COMPANY_LIST_STAT = "STA_CHEQUE_BY_COMPANY_LIST_STAT";
export const STA_CHEQUE_BY_COMPANY_LIST_STAT_BRANCH = "STA_CHEQUE_BY_COMPANY_LIST_STAT_BRANCH";
export const STA_CHEQUE_BY_COMPANY_LIST_STAT_CHEQUE = "STA_CHEQUE_BY_COMPANY_LIST_STAT_CHEQUE";
export const STA_CHEQUE_BY_COMPANY_LIST_STAT_REVENUE = "STA_CHEQUE_BY_COMPANY_LIST_STAT_REVENUE";

export const STA_CHEQUE_BY_COMPANY_LIST_FILT = "STA_CHEQUE_BY_COMPANY_LIST_FILT";
export const STA_CHEQUE_BY_COMPANY_LIST_FILT_DATE = "STA_CHEQUE_BY_COMPANY_LIST_FILT_DATE";
export const STA_CHEQUE_BY_COMPANY_LIST_FILT_SEARCH = "STA_CHEQUE_BY_COMPANY_LIST_FILT_SEARCH";
export const STA_CHEQUE_BY_COMPANY_LIST_FILT_REGION = "STA_CHEQUE_BY_COMPANY_LIST_FILT_REGION";
export const STA_CHEQUE_BY_COMPANY_LIST_FILT_CITY = "STA_CHEQUE_BY_COMPANY_LIST_FILT_CITY";

// Monitoring

export const MON_MENU = "MON_MENU";

// Companies

export const MON_COMPANY = "MON_COMPANY";
export const MON_COMPANY_LIST = "MON_COMPANY_LIST";
export const MON_COMPANY_LIST_FILT = "MON_COMPANY_LIST_FILT";
export const MON_COMPANY_LIST_FILT_DATE = "MON_COMPANY_LIST_FILT_DATE";
export const MON_COMPANY_LIST_FILT_SEARCH = "MON_COMPANY_LIST_FILT_SEARCH";
export const MON_COMPANY_LIST_FILT_ACTIVITY = "MON_COMPANY_LIST_FILT_ACTIVITY";
export const MON_COMPANY_LIST_FILT_BUSINESS = "MON_COMPANY_LIST_FILT_BUSINESS";

export const MON_COMPANY_DETAILS = "MON_COMPANY_DETAILS";
export const MON_COMPANY_DETAILS_STAT = "MON_COMPANY_DETAILS_STAT";
export const MON_COMPANY_DETAILS_STAT_CHEQUES = "MON_COMPANY_DETAILS_STAT_CHEQUES";
export const MON_COMPANY_DETAILS_STAT_BRANCHES = "MON_COMPANY_DETAILS_STAT_BRANCHES";
export const MON_COMPANY_DETAILS_STAT_KKM = "MON_COMPANY_DETAILS_STAT_KKM";
export const MON_COMPANY_DETAILS_STAT_REVENUE = "MON_COMPANY_DETAILS_STAT_REVENUE";
export const MON_COMPANY_DETAILS_STAT_PRODUCTS = "MON_COMPANY_DETAILS_STAT_PRODUCTS";
export const MON_COMPANY_DETAILS_STAT_TOTAL_COST_PRICE = "MON_COMPANY_DETAILS_STAT_TOTAL_COST_PRICE";
export const MON_COMPANY_DETAILS_STAT_TOTAL_SALES_PRICE = "MON_COMPANY_DETAILS_STAT_TOTAL_SALES_PRICE";

export const MON_COMPANY_DETAILS_BRANCHES = "MON_COMPANY_DETAILS_BRANCHES";
export const MON_COMPANY_DETAILS_KKMS = "MON_COMPANY_DETAILS_KKMS";
export const MON_COMPANY_DETAILS_USERS = "MON_COMPANY_DETAILS_USERS";
export const MON_COMPANY_DETAILS_LOGS = "MON_COMPANY_DETAILS_LOGS";
export const MON_COMPANY_DETAILS_CATALOG = "MON_COMPANY_DETAILS_CATALOG";
export const MON_COMPANY_DETAILS_CHEQUES = "MON_COMPANY_DETAILS_CHEQUES";
export const MON_COMPANY_DETAILS_STOCK = "MON_COMPANY_DETAILS_STOCK";
export const MON_COMPANY_DETAILS_STOCK_BY_DAY = "MON_COMPANY_DETAILS_STOCK_BY_DAY";
export const MON_COMPANY_DETAILS_INCOMES = "MON_COMPANY_DETAILS_INCOMES";
export const MON_COMPANY_DETAILS_INCOMES_ADD = "MON_COMPANY_DETAILS_INCOMES_ADD";
export const MON_COMPANY_DETAILS_PROMOTION = "MON_COMPANY_DETAILS_PROMOTION";
export const MON_COMPANY_DETAILS_PROMOTION_LIST = "MON_COMPANY_DETAILS_PROMOTION_LIST";
export const MON_COMPANY_DETAILS_PROMOTION_ADD = "MON_COMPANY_DETAILS_PROMOTION_ADD";
export const MON_COMPANY_DETAILS_PROMOTION_DETAILS = "MON_COMPANY_DETAILS_PROMOTION_DETAILS";
export const MON_COMPANY_DETAILS_DATA_ENTRY = "MON_COMPANY_DETAILS_DATA_ENTRY";


// Employee

export const MON_EMPLOYEE = "MON_EMPLOYEE";
export const MON_EMPLOYEE_LIST = "MON_EMPLOYEE_LIST";
export const MON_EMPLOYEE_LIST_FILT = "MON_EMPLOYEE_LIST_FILT";
export const MON_EMPLOYEE_LIST_FILT_SEARCH = "MON_EMPLOYEE_LIST_FILT_SEARCH";
export const MON_EMPLOYEE_LIST_FILT_COMPANY = "MON_EMPLOYEE_LIST_FILT_COMPANY";
export const MON_EMPLOYEE_LIST_FILT_BRANCH = "MON_EMPLOYEE_LIST_FILT_BRANCH";
export const MON_EMPLOYEE_EDIT = "MON_EMPLOYEE_EDIT";
export const MON_EMPLOYEE_UPDATE_LOGIN = "MON_EMPLOYEE_UPDATE_LOGIN";
export const MON_EMPLOYEE_DELETE_TOKEN = "MON_EMPLOYEE_DELETE_TOKEN";

// Branches

export const MON_BRANCH = "MON_BRANCH";
export const MON_BRANCH_LIST = "MON_BRANCH_LIST";
export const MON_BRANCH_LIST_FILT = "MON_BRANCH_LIST_FILT";
export const MON_BRANCH_LIST_FILT_DATE = "MON_BRANCH_LIST_FILT_DATE";
export const MON_BRANCH_LIST_FILT_COMPANY = "MON_BRANCH_LIST_FILT_COMPANY";
export const MON_BRANCH_LIST_FILT_SEARCH = "MON_BRANCH_LIST_FILT_SEARCH";
export const MON_BRANCH_DETAILS = "MON_BRANCH_DETAILS";

// KKM

export const MON_KKM = "MON_KKM";
export const MON_KKM_LIST = "MON_KKM_LIST";
export const MON_KKM_LIST_FILT = "MON_KKM_LIST_FILT";
export const MON_KKM_LIST_FILT_SEARCH = "MON_KKM_LIST_FILT_SEARCH";
export const MON_KKM_LIST_FILT_COMPANY = "MON_KKM_LIST_FILT_COMPANY";
export const MON_KKM_LIST_FILT_BRANCH = "MON_KKM_LIST_FILT_BRANCH";
export const MON_KKM_SYNC = "MON_KKM_SYNC";
export const MON_KKM_DELETE = "MON_KKM_DELETE";

// Logs

export const MON_LOG = "MON_LOG";
export const MON_LOG_LIST = "MON_LOG_LIST";

// Products

export const MON_PRODUCT = "MON_PRODUCT";
export const MON_PRODUCT_LIST = "MON_PRODUCT_LIST";
export const MON_PRODUCT_LIST_FILT = "MON_PRODUCT_LIST_FILT";
export const MON_PRODUCT_LIST_FILT_DATE = "MON_PRODUCT_LIST_FILT_DATE";
export const MON_PRODUCT_LIST_FILT_REGION = "MON_PRODUCT_LIST_FILT_REGION";
export const MON_PRODUCT_LIST_FILT_CITY = "MON_PRODUCT_LIST_FILT_CITY";
export const MON_PRODUCT_LIST_FILT_SEARCH = "MON_PRODUCT_LIST_FILT_SEARCH";

// services
export const MON_AGREEMENTS = "MON_AGREEMENTS";
export const MON_AGREEMENTS_LIST = "MON_AGREEMENTS_LIST";


// TG Users

export const MON_TG_USERS = "MON_TG_USERS";
export const MON_TG_USERS_LIST = "MON_TG_USERS_LIST";
export const MON_TG_USERS_LIST_FILT = "MON_TG_USERS_LIST_FILT";
export const MON_TG_USERS_LIST_FILT_SEARCH = "MON_TG_USERS_LIST_FILT_SEARCH";
export const MON_TG_USERS_LIST_FILT_COMPANY = "MON_TG_USERS_LIST_FILT_COMPANY";
export const MON_TG_USERS_LIST_FILT_BRANCH = "MON_TG_USERS_LIST_FILT_BRANCH";


// Suppliers

export const SUP_MENU = "SUP_MENU";

// Suppliers-companies

export const SUP_COMPANY = "SUP_COMPANY";
export const SUP_COMPANY_LIST = "SUP_COMPANY_LIST";
export const SUP_COMPANY_LIST_FILT_SEARCH = "SUP_COMPANY_LIST_FILT_SEARCH";

export const SUP_COMPANY_DETAILS = "SUP_COMPANY_DETAILS";
export const SUP_COMPANY_DETAILS_STAT = "SUP_COMPANY_DETAILS_STAT";
export const SUP_COMPANY_DETAILS_STAT_TOTAL_ORDERS = "SUP_COMPANY_DETAILS_STAT_TOTAL_ORDERS";
export const SUP_COMPANY_DETAILS_STAT_COMPLETE_ORDERS = "SUP_COMPANY_DETAILS_STAT_COMPLETE_ORDERS";
export const SUP_COMPANY_DETAILS_STAT_TOTAL_COMPLETE_AMOUNT = "SUP_COMPANY_DETAILS_STAT_TOTAL_COMPLETE_AMOUNT";

export const SUP_COMPANY_DETAILS_ORDERS = "SUP_COMPANY_DETAILS_ORDERS";

// Management

export const MAN_MENU = "MAN_MENU";

// Users

export const MAN_USER = "MAN_USER";
export const MAN_USER_LIST = "MAN_USER_LIST";
export const MAN_USER_LIST_FILT = "MAN_USER_LIST_FILT";
export const MAN_USER_LIST_FILT_SEARCH = "MAN_USER_LIST_FILT_SEARCH";
export const MAN_USER_ADD = "MAN_USER_ADD";
export const MAN_USER_EDIT = "MAN_USER_EDIT";

// Excise

export const MAN_EXCISE = "MAN_EXCISE";
export const MAN_EXCISE_LIST = "MAN_EXCISE_LIST";
export const MAN_EXCISE_LIST_FILT = "MAN_EXCISE_LIST_FILT";
export const MAN_EXCISE_LIST_FILT_SEARCH = "MAN_EXCISE_LIST_FILT_SEARCH";

export const MAN_EXCISE_ADD = "MAN_EXCISE_ADD";
export const MAN_EXCISE_EDIT = "MAN_EXCISE_EDIT";

// Vats

export const MAN_VAT = "MAN_VAT";
export const MAN_VAT_LIST = "MAN_VAT_LIST";
export const MAN_VAT_ADD = "MAN_VAT_ADD";
export const MAN_VAT_EDIT = "MAN_VAT_EDIT";
export const MAN_VAT_DELETE = "MAN_VAT_DELETE";

// Units

export const MAN_UNIT = "MAN_UNIT";
export const MAN_UNIT_LIST = "MAN_UNIT_LIST";

export const MAN_SINGLE_CAT = "MAN_SINGLE_CAT";
export const MAN_SINGLE_CAT_UPLOAD = "MAN_SINGLE_CAT_UPLOAD";
export const MAN_SINGLE_CAT_DOWNLOAD = "MAN_SINGLE_CAT_DOWNLOAD";